### ISSUE TITLE
[CCPA] legislation selection on form

### ISSUE THREAD

**Issue by roughprada** [your-digital-rights/yourdigitalrights.org#108]
Design and implement a way for the user to select legislation (GDPR or CCPA)

**Comment by limptwiglet** [comment]
What effect does this have on the email that get generated? @roughprada

**Comment by roughprada** [comment]
It should use a different template for the email. @yoavaviram do we have the content of the email or we just start with a placeholder file?

**Comment by yoavaviram** [comment]
https://drive.google.com/open?id=1OTQBAwcXlEj93Z8cMPujte8GxqhcI0XdiDC6r6h7z1Q

**Comment by roughprada** [comment]
@yoavaviram this is the ticket for the CCPA template, not the SAR one

**Comment by yoavaviram** [comment]
Sorry, no still don't have a template for this.
