### ISSUE TITLE
[content] Cookie consent

### ISSUE THREAD

**Issue by roughprada** [your-digital-rights/yourdigitalrights.org#110]
We need to create a banner notifying the user about how do we use cookies and that if they select do not use cookies, we still allow them to finish the submission.

Only a few lines to then create a banner would be enough.

Design and copy: https://zpl.io/VOnLo68

**Comment by limptwiglet** [comment]
So they have the option to disable the use of any cookies we or 3rd parties add to their browser?

**Comment by roughprada** [comment]
Yes, that will be the ideal scenario. We should preach with an example :)

**Comment by yoavaviram** [comment]
That would be great. We already use a cookie for analytics. The fallback should be to tell Matomo not to use cookies (here's how: https://matomo.org/faq/general/faq_157/). Both options (analytics + remembering user choices) should be selected by default.

**Comment by roughprada** [comment]
here you can find 2 samples of cookies that can be presented as optional.

![Screenshot 2019-10-25 at 14 29 53](https://user-images.githubusercontent.com/5957010/67577075-ad0bbb80-f737-11e9-91f7-06927eef71e0.png)
![Screenshot 2019-10-25 at 14 31 27](https://user-images.githubusercontent.com/5957010/67577076-ada45200-f737-11e9-872d-b908c718f5a6.png)

**Comment by yoavaviram** [comment]
Just to correct the initial note, we use one kind of cookie today, for analytics. Also, cookies are not something you share with others so the copy in the design is not correct.

**Comment by roughprada** [comment]
updated design on the notes
