### ISSUE TITLE
[Organization page] Clipboard functionality

### ISSUE THREAD

**Issue by roughprada** [your-digital-rights/yourdigitalrights.org#125]
After clicking "review your request" on the organization page, we will present with the selected template (deletion or data request) with the following design:

Design: https://zpl.io/amNkKPQ

When click "open in your email" it will do as usual (mailto)
When click "copy to the clipboard" it shows the message "

Only to develop the copy and paste functionality, not the elements that have a red square (WIP)

**Comment by roughprada** [comment]
@yoavaviram can you add some of the requirements here?

**Comment by yoavaviram** [comment]
The requirement is to allow the user to copy the generated template to the clipboard.
