### ISSUE TITLE
[global styling] Thank you page and subtitle on about us

### ISSUE THREAD

**Issue by roughprada** [your-digital-rights/yourdigitalrights.org#134]
About us

<img width="945" alt="Screenshot 2020-01-10 at 10 02 51" src="https://user-images.githubusercontent.com/5957010/73089056-5a27d880-3ecd-11ea-875f-2c861b9cb97a.png">

H1 highlight

<img width="696" alt="Screenshot 2020-01-10 at 10 00 20" src="https://user-images.githubusercontent.com/5957010/73089057-5a27d880-3ecd-11ea-92c9-c1319a7c889b.png">

**Comment by yoavaviram** [comment]
What is this about?
