### ISSUE TITLE
Update Browser extensions

### ISSUE THREAD

**Issue by roughprada** [your-digital-rights/yourdigitalrights.org#147]
To update  the browser extension with the latest changes from the app:

- [ ] The icon is always active.
- [ ] If the domain is in our list, we will take the user to the screen
- [ ] If the domain is not on our list, we will take them to ADD a new org.
- [ ] The icon is now red, we should upload all new visual references

We should then upload the app to the following:
- Chrome & Brave
- FIrefox
- Safari
  - [ ] Create artworks
  - [ ] Add the button to site

**Comment by yoavaviram** [comment]
@roughprada update with what?

**Comment by roughprada** [comment]
@yoavaviram just updated the ticket. A few months ago when I tried to upload the browser with the new icons, Chrome asked me for a bunch of security questions that I'm sure you'd have already answered somewhere. We can look into this at some point.
