### ISSUE TITLE
Where is the data?

### ISSUE THREAD

**Issue by viveksh1** [your-digital-rights/yourdigitalrights.org#221]
Could you please make your data public? Maybe something like [this.](https://github.com/datenanfragen/data)

**Comment by yoavaviram** [comment]
Our data is available via [this](api.yourdigitalrights.org/companies) API endpoint. Please make fair use of the API and note that the data is licensed under GPLv3. 

May I ask what are you intending to use the data for?

**Comment by VladPutinEu** [comment]
> Our data is available via [this](https://api.yourdigitalrights.org/companies) API endpoint. Please make fair use of the API and note that the data is licensed under GPLv3.
> 
> May I ask what are you intending to use the data for?

@yoavaviram Apologies for the delay. I want to use the data so I can create an application that allows users to import their password file which is exported from a password manager into the application. They will then enter their email address and select the accounts they want to be deleted. The application will then use the data from yourdigitalrights.org to find the email addresses and automate the sending of GDPR/CCPA requests. There currently no viable too that automates the deletion of accounts, this is the first.

**Comment by yoavaviram** [comment]
Hi @VladPutinEu , I get what you are trying to do - getting a list of accounts for a user and then offering a way to easily delete these accounts would be great, however I would not ask users to upload their password list to my service, even if it never reaches your servers. It's too risky as there are too many ways this can be abused. In any case I wish you all the best!

**Comment by VladPutinEu** [comment]
> Hi @VladPutinEu , I get what you are trying to do - getting a list of accounts for a user and then offering a way to easily delete these accounts would be great, however I would not ask users to upload their password list to my service, even if it never reaches your servers. It's too risky as there are too many ways this can be abused. In any case I wish you all the best!

No, I am planning to make sure that the application will be open-source and everything will be done locally, the application will only need internet access to send the GDPR/CCPA emails.

**Comment by yoavaviram** [comment]
I'd love to see it when you've got something to show.
