### ISSUE TITLE
Investigate options to run aws-backend locally

### ISSUE THREAD

**Issue by richerve** [your-digital-rights/yourdigitalrights.org#233]
It should be possible to test changes to backend components in a local environment instead of the cloud, and if not, that should be documented properly.

Currently, infrastructure deployed using the CDK, only works in the cloud. There's no way to re-use the same code to deploy to a local "instance" of a service, so testing and verification need to happen in AWS directly.

There are many advantages of using the CDK to provision and manage cloud resources, so it would be ideal to avoid having to duplicate code in order to deploy resources in a local copy or mockup service.

**Comment by richerve** [comment]
This issue depends on https://github.com/your-digital-rights/yourdigitalrights.org/issues/232, as without that doing local testing is very hard or not possible because of components that don't have parallel in a local environment like SES receiving email

**Comment by richerve** [comment]
One way of using the CDK code and execute it locally is by using [AWS' SAM](https://aws.amazon.com/serverless/sam/) to use a local render output of the CloudFormation template done by the CDK and invoke for example a lambda function defined in it. This method works but it has many limitations:
- Can only invoke lambda functions and only in case all variables are defined in one stack, if not, SAM doesn't know how to resolve the CloudFormation template created by the CDK.
- It doesn't work with DynamoDB, so it's not possible to have a local recreation of the DB for development or testing.
- SAM has also commands to deploy serverless "objects" that are irrelevant when using the CDK, so there's a multi step process in order to make it work with the CDK.

AWS has addressed some of those shortcomings with a beta version of SAM that is more integrated with the CDK: https://aws.amazon.com/blogs/compute/better-together-aws-sam-and-aws-cdk/. With this, for example, it's possible to invoke a lambda function using SAM without the intermediate step of generation the cloudformation template with the CDK first. But again, it focuses on lambda execution and not in surrounding components.

**Comment by richerve** [comment]
I found another option to deploy AWS services locally that is very powerful and on my testing showed to be working very well. It's an open source tool called [LocalStack](https://github.com/localstack/localstack). What it does is basically have a local service replicating (mocking) AWS responses and receiving calls from the aws cli or sdk. LocalStack leverages the `--endpoint-url` flag in the aws cli and equivalent option for the sdk, to target the local service instead of AWS' API.

LocalStack is written in python, but can run in docker so no extra dependency would be needed if using the containerized version.

LocalStack can mimic DynamoDB, Lambda, SNS and even SES so it should be possible to build at least integration tests around that. It has a Pro (paid) version that include other services, but we don't use any of those as are mostly target at enterprise usage. In the overview they specify what services are included for free and which ones are included in pro: https://github.com/localstack/localstack#overview

**Comment by richerve** [comment]
So my proposal is to focus in using LocalStack for the moment and keep checking CDK and SAM updates in case they improve in their integration and can possibly replace LocalStack in the future

**Comment by yoavaviram** [comment]
Very interesting, lets discuss on the call today.
