### ISSUE TITLE
mailgo popup is not shown for company email address without a dot

### ISSUE THREAD

**Issue by gianantoniopini** [your-digital-rights/yourdigitalrights.org#248]
If I enter an organization email address like "user@mail" (without a ".") in the Personal Info Form (d/add url), fill in all the other mandatory fields and then click on "Review your request" button, then the _mailgo_ popup is not shown but the "Thank You" message is still shown.
Although this is an unlikely scenario, it might still be better to try and fix it.

The problem is due to the fact that the HTML5 form-validation (`type="email"`) currently in place treats emails without a dot as valid while the email validation performed internally by mailgo treats such emails as invalid.

One solution would be to use the `mailgoValidateEmail` function provided by mailgo to perform validation of the organization email address. This validation would be done before mailgo gets rendered. In this way the email validation will be performed consistently between the form and mailgo. So if the user enters an email address like "user@mail" a validation error will be shown.

Should we fix this? I would be happy to work on this issue.

**Comment by yoavaviram** [comment]
HI @gianantoniopini , thanks for reporting this issue, it's nice hear from you. Sure, it would be nice if you can send a PR for this.

**Comment by gianantoniopini** [comment]
Hi @yoavaviram , thanks. Nice to hear from you too :-) I will look into this issue.
