### ISSUE TITLE
Email address for oracle opt out bounces

### ISSUE THREAD

**Issue by agotsis** [your-digital-rights/yourdigitalrights.org#267]
In the US, https://yourdigitalrights.org/d/oracle.com sends mail to customer_us@oracle.com.

This email address does not exist.

`550 5.1.1 Unknown recipient address.`

**Comment by yoavaviram** [comment]
Hi @agotsis , thanks for letting us know!

We have now replaced the email address you reported with a different one. The website should be updated within an hour. If you try again please let me know if it works.
