### ISSUE TITLE
TikTok has updated their contact method

### ISSUE THREAD

**Issue by BadCoder2** [your-digital-rights/yourdigitalrights.org#282]
Previously (and what is utilized currently,) TikTok received legal requests through legal@tiktok.com. However, after November 1st 2021, they only accept legal emails through lert@tiktok.com.

**Comment by BadCoder2** [comment]
I was digging through the code and found [where the emails are stored](https://api.yourdigitalrights.org/companies) but I can't find any mention of this in the code except for where it is actually pulled from the API directly, and I don't see a way to push PRs to there directly. That said, it should be a pretty easy control-f, replace "legal" with "lert," and push.

**Comment by roughprada** [comment]
Thanks, @BadCoder2 . We have the database separated from the code, but I will make sure I change the contact email from this organisation. COuld I please ask you how you find out about this change?

**Comment by BadCoder2** [comment]
> Thanks, @BadCoder2 . We have the database separated from the code, but I will make sure I change the contact email from this organisation. Could I please ask you how you find out about this change?

When I attempted to get my data from TikTok, I was replied to with a message saying that legal@tiktok.com is no longer being maintained.
---
That said, I tried emailing their new lert@tiktok.com email and received the following notice:
![image](https://user-images.githubusercontent.com/46334485/146697566-70b0e218-b579-4b14-b9cf-956875ebf58f.png)
It appears they have redirected this sort of traffic to https://www.tiktok.com/legal/report/privacy.

**Comment by yoavaviram** [comment]
Hi @BadCoder2 , sorry for jumping into the conversation. After some research I managed to find out that TikTok have another email address (privacy@tiktok.com) which they only show to users in the EU. I've updated the service. Please test it and let us know how it goes. Thanks for letting us know in the first place!

**Comment by BadCoder2** [comment]
Thanks for the idea @yoavaviram! Unfortunately, upon emailing them receive the same message as legal@tiktok.com:
![image](https://user-images.githubusercontent.com/46334485/146798135-1696e067-fe07-4076-b397-cf6ea94bd72b.png)
From what I can tell, it appears they force users to use their webform for privacy-related queries like this.

**Comment by yoavaviram** [comment]
Hi @BadCoder2, thanks for the update. I've done some more research and updated the email address again. This one seems to accept emails, please test and let us know.

**Comment by yoavaviram** [comment]
Hi @BadCoder2 , I've updated the email again, this time using `info@tiktok.com`. Please try it and let me know how it goes.
