### ISSUE TITLE
display 0 on the searchbar

### ISSUE THREAD

**Issue by roughprada** [your-digital-rights/yourdigitalrights.org#283]
When I type something on the search bar and then delete the full text, on the results, it appears a "0".
The expected behaviour should be not to show anything, only the "can't find and org" button

<img width="1552" alt="Screenshot 2021-12-16 at 08 59 20" src="https://user-images.githubusercontent.com/5957010/146895066-8c4233c0-5668-4f2f-ba25-7df3addd970f.png">

**Comment by apoc146** [comment]
Hi!  @roughprada.
Could you review my fix for the issue.

**Comment by yoavaviram** [comment]
Thanks @apoc146 !

**Comment by apoc146** [comment]
Thanks @yoavaviram for the review. Looking forward to contribute. 
I was wondering if my commit email could be corrected since it seems to have caught a trailing character. It's totally fine if its too much of a hassle, wouldn't want to dirty the history.

**Comment by yoavaviram** [comment]
Hi @apoc146 , no worries, better to leave it the way it is then to re-write the history.
