### ISSUE TITLE
Contact email for Neowin.net does not exist (May 2022)

### ISSUE THREAD

**Issue by evelineraine** [your-digital-rights/yourdigitalrights.org#357]
The contact email address for Neowin.net specified in your database - privacy@neowin.net - no longer exists. My email bounced on May 31, 2022.

```
Reporting-MTA: dns; googlemail.com
Arrival-Date: Tue, 31 May 2022 14:30:24 -0700 (PDT)
X-Original-Message-ID: <...@mail.gmail.com>

Final-Recipient: rfc822; privacy@neowin.net
Action: failed
Status: 5.1.1
Diagnostic-Code: smtp; 550-5.1.1 The email account that you tried to reach does not exist. Please try
 550-5.1.1 double-checking the recipient's email address for typos or
 550-5.1.1 unnecessary spaces. Learn more at
 550 5.1.1  https://support.google.com/mail/?p=NoSuchUser t9-20020a056808158900b003222511c455sor23110oiw.48 - gsmtp
Last-Attempt-Date: Tue, 31 May 2022 14:30:25 -0700 (PDT)
```

In the end, my request was satisfied when I submitted it via https://www.neowin.net/contact/ page.

While their Privacy Policy page (https://www.neowin.net/privacy/) still lists privacy@neowin.net, it also explicitly directs to the above web page for data deletion requests.

**Comment by yoavaviram** [comment]
Thanks @evelineraine ! We've updated our database with an alternative address.
