### ISSUE TITLE
invalid email for OkCupid

### ISSUE THREAD

**Issue by karlicoss** [your-digital-rights/yourdigitalrights.org#382]
Hi! When making a request to OkCupid, yourdigitalrights.org suggests emailing to `copyright@match.com`. 

However, I got this response from that address

> Thank you for your email. Please note that we are uncertain which dating service you are attempting to contact.
> We suggest for you to visit their Privacy Policy or Help section for information on how to submit your request appropriately.
> Please note that the Copyright Team is available to assist with Intellectual Property claims, which your concern does not appear to be. 

So after that I emailed the same template to `support@okcupid.com` -- this time they responded, requested additional documents (government issued ID), and after that I got my data export. So I believe the address for OkCupid should be `support@okcupid.com` 

Thanks!

**Comment by yoavaviram** [comment]
Thanks @karlicoss ! We've updated our database.
