### ISSUE TITLE
33mileradius.com

### ISSUE THREAD

**Issue by tomle** [your-digital-rights/yourdigitalrights.org#383]
CCPA requests to EverCommerce.com are getting rejected by their legal department saying:

> Please note that EverCommerce Legal represents several independent wholly owned subsidiaries. Any requests that you may have for an EverCommerce subsidiary company must be provided directly to that entity as provided in clear instructions with the California Data Broker Registry. Your request did not indicate the entity to which your request 

The privacy policy on 33mileradius.com points to https://www.everconnect.com/privacy-policy/ but the text signature at the bottom is signed by privacy@33mileradius.com.

Suggestion:  Update email address at https://yourdigitalrights.org/d/33mileradius.com to mail to privacy@33mileradius.com

**Comment by yoavaviram** [comment]
Thanks @tomle ! We've updated our database.
