### ISSUE TITLE
Epic Games has changed their email

### ISSUE THREAD

**Issue by metezd** [your-digital-rights/yourdigitalrights.org#459]
Old email dpo@epicgames.com no longer in use, new one is dpo@support.epicgames.com

You can see it in section 10 of Epic Games' [Privacy Policy](https://www.epicgames.com/site/en-US/privacypolicy)

> If you live in the EEA, the UK, or Switzerland and you are using: the data controller is: contact information: the Epic Games Store Epic Games, Inc. 620 Crossroads Blvd., Cary, NC 27518, USA For any questions or concerns about the handling of personal data, contact our Data Protection Officer at dpo@support.epicgames.com.

**Comment by yoavaviram** [comment]
Thanks @metezd for your report! We have updated our database.
