### ISSUE TITLE
Roblox.com has the wrong email.

### ISSUE THREAD

**Issue by dr-kamil1** [your-digital-rights/yourdigitalrights.org#487]
Requesting data from roblox.com will use info@roblox.com
The correct mails are as follows (from https://en.help.roblox.com/hc/en-us/articles/115004630823)
If you have any questions, comments, or concerns regarding this Privacy Policy and/or our data practices, please contact us at the following support form, telephone number, or mailing address:

[Customer Support Form](https://www.roblox.com/support)
[...]
privacy@roblox.com

For users based in the European Economic Area (EEA), the United Kingdom, or Switzerland, you may also contact our Representative according to Articles 17 EU and UK GDPR in the European Union:

roblox@gdpr-rep.com

**Comment by yoavaviram** [comment]
@dr-kamil1, thanks for reporting. We have updated our database with the new email. Our production system will update in up to 24h.
