### ISSUE TITLE
Frame.io email does not work

### ISSUE THREAD

**Issue by jeikashu** [your-digital-rights/yourdigitalrights.org#524]
The email privacy@frame.io is not accessible. I think it should be changed to support@frame.io.
![image](https://github.com/your-digital-rights/yourdigitalrights.org/assets/25012611/e7b9e2e2-0d4e-4e1f-b8da-a9f5544be28c)

**Comment by yoavaviram** [comment]
Thanks for reporting @jeikashu. We have updated the email in our database.
