### ISSUE TITLE
[Thank you] Review on 'Success state'

### ISSUE THREAD

**Issue by roughprada** [your-digital-rights/yourdigitalrights.org#66]
Design: https://zpl.io/bWRPO3j
Test: https://opt-out-eu-csspmotytj.now.sh/

---------------------------------

- [x] can we centre "thank you"?
- [x] bottom margin on the white box to 20px
- [x] blue box padding to 50px (currently 20px)
- [x] Remove bol from the font
- [x] H1 margin-bottom to 20px
- [x] On mobile, icons to be all in the same line (horizontal) - maybe reducing side padding to 10px
- [x] Meta title: can we change it to "Opt-out - Own your data"
- [x] Can we attached an image for the preview in social media?
- [x] When click on the button "find another company" behaviour is correct to focus on the search box, however, is there a way to do the anchor point to the top of the hero? currently only scrolls to the search bar.
- [ ] Social sharing icons are not shown in Chrome with uBlock
- [x] We should open email sharing in a separate window.
- [x] LinkedIn, Twitter and FB sharing dialogs don’t show a picture or display a text.
- [x] Update copy
- [x] Remove Github Link

 For some reason opening the link to the FAQ in a new window (command + click) does not scroll to the FAQs.

**Comment by limptwiglet** [comment]
We had a og:image meta tag but it was pointing to an svg, it seems that svg files are not picked up for sharing. I have switched it to the one that @roughprada provided to me. Outside of that the social sharing components we are using are just simple wrappers around basic sharing links so we may not be able to configure images.

**Comment by limptwiglet** [comment]
Latest deployment is https://opt-out-eu-zdjkduewil.now.sh/
