### ISSUE TITLE
[Thank you] Copy for social links

### ISSUE THREAD

**Issue by roughprada** [your-digital-rights/yourdigitalrights.org#67]
**Linkedin**
Img: https://drive.google.com/file/d/19TpBKFTbTM7sQ2dMBPC-TWuofoM31QmU/view?usp=sharing

**Twitter**
Text: Get any organisation to erase your personal data - automated GDPR requests - http://opt-out.eu @OptoutEU #privacy #privacy #GDPR #ownyourdata #righttobeforgotten #optout

**Mail**
Subject: Opt-out - automated GDPR requests
Body:
Hey there,
Did you know that you can get any organisation to erase your personal data for free?
Check out http://opt-out.eu to know more.

**Facebook**
Img: https://drive.google.com/file/d/19TpBKFTbTM7sQ2dMBPC-TWuofoM31QmU/view?usp=sharing
Text: Get any organisation to erase your personal data - automated GDPR requests - http://opt-out.eu

**Comment by yoavaviram** [comment]
@roughprada we already have copy for social sharing in https://docs.google.com/document/d/1Pl02ycvvFB5PcAFm8Zc3lIkPH9qyImVti9pW038-9uU/edit#heading=h.gxb499se6mi0. If you want to add specific copy for Twitter/email etc. Please add it there. I'd like to keep all the copy in that document.

**Comment by roughprada** [comment]
@yoavaviram I commented it on trello, here the copy:
I don't think that a single line works for all of the media as we missed handles, ashtags and all that depending on the platform. If you can review the options we have in this card, I can update the document with the latest updates.
